
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
idol_card = {suit = 'Spades', rank = 'Ace'},
mail_card = {rank = 'Ace'},
ancient_card = {suit = 'Spades'},
'''
position = 'after'
payload = '''
young_card = {suit = 'Spades'},
old_card = {suit = 'Spades'},
'''
match_indent = true